<a href="https://colab.research.google.com/github/kmahatma/ssmi-patternrecognition/blob/main/week02_02_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 2.	Matrix
# Matriks adalah basic 2D table dari data dan dapat berisi nilai numerik dan/atau karakter.
# Dapat dibuat dengan cara sederhana dengan membuat urutan dari vektor, mengubah dari vektor atau membaca dari file

# mengubah dari 1D menjadi matrik 2D
# Import numpy
import numpy as np

# Generate a 1D array
a = np.arange(1, 21, 1)

# Reshape into a 2D matrix (4 rows, 5 columns)
c = a.reshape((4, 5))

# Print the matrix
print("Matriks 4x5 dari vektor 1D:\n", c)

Matriks 4x5 dari vektor 1D:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
