<a href="https://colab.research.google.com/github/kmahatma/ssmi-patternrecognition/blob/main/week02_01_vektor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1.	Vektor
# Deklarasi variabel diawali dengan
# Vektor dapat dituliskan dengan dan tanpa bantuan libarary

# vektor python numpy with range value import numpy as np
# Import the required library
import numpy as np

# Vektor default Python using numpy.arange
print("vektor default python\n")
a = np.arange(1, 20, 1)
b = np.arange(1, 20, 2)

# Display vectors
print(a)
print(b)

# Vektor via numpy
print("\nvektor via numpy\n")
c = np.array([1, 2, 3, 4, 5])
d = np.array([1.5, 2.5, 5, 6, 7])

# Display arrays
print(c)
print(d)

# Print shape and dimensions of 'a'
print("Dimensi a:", a.ndim)
print("Shape a:", a.shape)


vektor default python

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]

vektor via numpy

[1 2 3 4 5]
[1.5 2.5 5.  6.  7. ]
Dimensi a: 1
Shape a: (19,)


# New section